import 'package:eco/core/app_export.dart';import 'package:eco/widgets/app_bar/appbar_leading_image.dart';import 'package:eco/widgets/app_bar/appbar_subtitle_five.dart';import 'package:eco/widgets/app_bar/appbar_subtitle_one.dart';import 'package:eco/widgets/app_bar/custom_app_bar.dart';import 'package:eco/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class ChatScreen extends StatelessWidget {ChatScreen({Key? key}) : super(key: key);

TextEditingController searchController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 29.h, vertical: 9.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildYesterday(context), SizedBox(height: 14.v), Padding(padding: EdgeInsets.only(right: 150.h), child: _buildIMFineWhatBout(context, messageText: "when are you ready??", messageTime: "06:30pm")), SizedBox(height: 16.v), Align(alignment: Alignment.centerRight, child: Container(margin: EdgeInsets.only(left: 119.h), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.customBorderTL201), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 185.v, width: 237.h, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.bottomCenter, child: Container(padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 12.v), decoration: AppDecoration.outlineBlack9006.copyWith(borderRadius: BorderRadiusStyle.roundedBorder5), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Container(width: 198.h, margin: EdgeInsets.only(right: 17.h), child: Text("David Austin, Who Breathed Life Into \nthe Rose, Is Dead at 92", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.labelMediumSFProTextBluegray80002Bold.copyWith(height: 1.21))), SizedBox(height: 8.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgEllipse3120x20, height: 20.adaptSize, width: 20.adaptSize, radius: BorderRadius.circular(10.h)), Padding(padding: EdgeInsets.only(left: 6.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Shivani Vora", style: CustomTextStyles.sFProTextBluegray80002), SizedBox(height: 3.v), Text("2019 . 01 . 01", style: CustomTextStyles.sFProTextPrimaryContainer)]))])]))), CustomImageView(imagePath: ImageConstant.imgRectangle22103x237, height: 103.v, width: 237.h, radius: BorderRadius.vertical(top: Radius.circular(9.h)), alignment: Alignment.topCenter)])), SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(left: 11.h), child: Text("Check this out.", style: CustomTextStyles.labelLargeMedium)), SizedBox(height: 1.v), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(right: 12.h), child: Text("08:33pm", style: CustomTextStyles.sFProDisplayBlack900))), SizedBox(height: 4.v)]))), SizedBox(height: 5.v)])), bottomNavigationBar: _buildSearch(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 104.v, leadingWidth: 43.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIconlyLightOu, margin: EdgeInsets.only(left: 32.h, top: 38.v, bottom: 28.v), onTap: () {onTapIconlyLightOu(context);}), centerTitle: true, title: Column(children: [AppbarSubtitleOne(text: "Amina Mark"), SizedBox(height: 4.v), AppbarSubtitleFive(text: "Last seen 2hrs ago", margin: EdgeInsets.only(left: 8.h, right: 5.h))]), styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildYesterday(BuildContext context) { return SizedBox(height: 161.v, width: 356.h, child: Stack(alignment: Alignment.topLeft, children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 138.h), child: Column(mainAxisSize: MainAxisSize.min, children: [Text("Yesterday", style: CustomTextStyles.labelMediumSFProDisplayBlack900), SizedBox(height: 137.v), Text("Today 06:30pm", style: CustomTextStyles.labelMediumSFProDisplayBlack900)]))), Padding(padding: EdgeInsets.only(top: 24.v), child: _buildIMFineWhatBout(context, messageText: "Hey, How are you today?", messageTime: "12:31pm")), Padding(padding: EdgeInsets.only(bottom: 32.v), child: _buildIMFineWhatBout(context, messageText: "I’m fine, what bout you?", messageTime: "12:32pm"))])); } 
/// Section Widget
Widget _buildSearch(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 20.h, right: 20.h, bottom: 23.v), child: CustomTextFormField(controller: searchController, hintText: "Type here to search", hintStyle: CustomTextStyles.bodyLargeSFProDisplayBlack900, textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.fromLTRB(16.h, 15.v, 5.h, 15.v), child: CustomImageView(imagePath: ImageConstant.imgPlusPrimary, height: 27.adaptSize, width: 27.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 59.v), suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 10.v, 16.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgSend, height: 39.adaptSize, width: 39.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 59.v), contentPadding: EdgeInsets.symmetric(vertical: 18.v), borderDecoration: TextFormFieldStyleHelper.outlineBlack)); } 
/// Common widget
Widget _buildIMFineWhatBout(BuildContext context, {required String messageText, required String messageTime, }) { return Container(padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 4.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.customBorderTL201), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 6.v), Text(messageText, style: CustomTextStyles.labelLargeMedium.copyWith(color: appTheme.black900)), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(right: 1.h), child: Text(messageTime, style: CustomTextStyles.sFProDisplayBlack900.copyWith(color: appTheme.black900))))])); } 
/// Navigates to the chatListScreen when the action is triggered.
onTapIconlyLightOu(BuildContext context) { Navigator.pushNamed(context, AppRoutes.chatListScreen); } 
 }
