import '../chat_list_share_screen/widgets/playlist_item_widget.dart';import '../chat_list_share_screen/widgets/unsplashfiqtetllw1_item_widget.dart';import 'package:eco/core/app_export.dart';import 'package:eco/widgets/app_bar/appbar_leading_image.dart';import 'package:eco/widgets/app_bar/appbar_subtitle_one.dart';import 'package:eco/widgets/app_bar/custom_app_bar.dart';import 'package:eco/widgets/custom_search_view.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class ChatListShareScreen extends StatelessWidget {ChatListShareScreen({Key? key}) : super(key: key);

TextEditingController searchController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Container(height: mediaQueryData.size.height, width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 23.v), child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.bottomLeft, child: Padding(padding: EdgeInsets.only(left: 63.h, bottom: 86.v), child: Text("On my way dear", style: CustomTextStyles.bodySmallBluegray200))), _buildPlaylist(context), _buildChatListShare(context)])))); } 
/// Section Widget
Widget _buildPlaylist(BuildContext context) { return Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(top: 341.v), child: ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 16.v);}, itemCount: 7, itemBuilder: (context, index) {return PlaylistItemWidget();}))); } 
/// Section Widget
Widget _buildChatListShare(BuildContext context) { return Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(left: 8.h, top: 44.v, right: 8.h), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomAppBar(height: 31.v, leadingWidth: 50.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIconlyLightOu, margin: EdgeInsets.only(left: 39.h, top: 11.v), onTap: () {onTapIconlyLightOu(context);}), centerTitle: true, title: AppbarSubtitleOne(text: "People")), SizedBox(height: 15.v), Padding(padding: EdgeInsets.only(left: 23.h, right: 21.h), child: CustomSearchView(controller: searchController, hintText: "Type here to search")), SizedBox(height: 27.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 2.h), child: Text("Frequently chatted", style: CustomTextStyles.titleMediumSFProDisplayBlack900Medium))), SizedBox(height: 6.v), SizedBox(height: 73.v, child: ListView.separated(padding: EdgeInsets.only(left: 2.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 18.h);}, itemCount: 4, itemBuilder: (context, index) {return Unsplashfiqtetllw1ItemWidget();})), SizedBox(height: 27.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 2.h), child: Text("All Messages", style: CustomTextStyles.titleSmallSFProDisplay_1))), SizedBox(height: 69.v)]))); } 
/// Navigates to the mainScreen when the action is triggered.
onTapIconlyLightOu(BuildContext context) { Navigator.pushNamed(context, AppRoutes.mainScreen); } 
 }
