import 'package:eco/core/app_export.dart';import 'package:eco/widgets/app_bar/appbar_leading_image.dart';import 'package:eco/widgets/app_bar/appbar_trailing_image.dart';import 'package:eco/widgets/app_bar/custom_app_bar.dart';import 'package:eco/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';class DetailPlantScreen extends StatelessWidget {const DetailPlantScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.onPrimary, body: SizedBox(width: double.maxFinite, child: Column(mainAxisSize: MainAxisSize.min, children: [_buildSixtyEight(context), Container(padding: EdgeInsets.symmetric(horizontal: 36.h, vertical: 43.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 5.v), Text("Caption", style: CustomTextStyles.headlineMediumGray400), SizedBox(height: 28.v), Row(children: [Text("Optional title", style: CustomTextStyles.titleSmallSFProTextGray400), Padding(padding: EdgeInsets.only(left: 26.h), child: Text("Optional title", style: CustomTextStyles.titleSmallSFProTextGray400))]), SizedBox(height: 11.v), Row(children: [Text("des-", style: CustomTextStyles.bodyMediumSFProTextBluegray20002_1), Padding(padding: EdgeInsets.only(left: 85.h), child: Text("des-", style: CustomTextStyles.bodyMediumSFProTextBluegray20002_1))]), SizedBox(height: 31.v), Text("Description", style: CustomTextStyles.titleSmallSFProTextBluegray700), SizedBox(height: 10.v), Container(width: 321.h, margin: EdgeInsets.only(right: 20.h), child: Text("Spinach is thought to have originated in ancient \nPersia (modern Iran and neighboring countries). \nIt is not known by whom, or when, spinach was \nintroduced to India, but the plant was subsequ\nently introduced to ancient China, where it was \nknown as \"Persian vegetable\" ", maxLines: 8, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumSFProTextBluegray20002_2)), SizedBox(height: 28.v), Text("Tag", style: CustomTextStyles.titleSmallSFProTextBluegray700), SizedBox(height: 10.v), Text("#loream", style: CustomTextStyles.titleSmallSFProTextGray400), SizedBox(height: 12.v), Text("#loream", style: CustomTextStyles.titleSmallSFProTextGray400)]))])), bottomNavigationBar: _buildUpload(context))); } 
/// Section Widget
Widget _buildSixtyEight(BuildContext context) { return SizedBox(height: 306.v, width: double.maxFinite, child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgRectangle62, height: 306.v, width: 414.h, alignment: Alignment.center), CustomAppBar(height: 84.v, leadingWidth: 47.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 23.h), onTap: () {onTapArrowLeft(context);}), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgGroup21, margin: EdgeInsets.only(left: 23.h, right: 23.h, bottom: 2.v), onTap: () {onTapImage(context);})])])); } 
/// Section Widget
Widget _buildUpload(BuildContext context) { return CustomElevatedButton(height: 59.v, text: "Upload", margin: EdgeInsets.only(left: 50.h, right: 50.h, bottom: 36.v), buttonStyle: CustomButtonStyles.outlineBlackTL29, buttonTextStyle: CustomTextStyles.headlineMediumSFProDisplayPrimary, onPressed: () {onTapUpload(context);}); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the settingsScreen when the action is triggered.
onTapImage(BuildContext context) { Navigator.pushNamed(context, AppRoutes.settingsScreen); } 
/// Navigates to the mainScreen when the action is triggered.
onTapUpload(BuildContext context) { Navigator.pushNamed(context, AppRoutes.mainScreen); } 
 }
