import 'package:eco/core/app_export.dart';import 'package:eco/widgets/custom_elevated_button.dart';import 'package:eco/widgets/custom_pin_code_text_field.dart';import 'package:flutter/material.dart';class VerificationScreen extends StatelessWidget {const VerificationScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 27.h, vertical: 40.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 39.v), CustomImageView(imagePath: ImageConstant.imgIconlyLightOu, height: 20.v, width: 11.h, margin: EdgeInsets.only(left: 2.h), onTap: () {onTapImgIconlyLightOu(context);}), SizedBox(height: 35.v), Text("OTP sent", style: theme.textTheme.titleLarge), SizedBox(height: 11.v), Opacity(opacity: 0.7, child: Text("Enter the OTP sent to you", style: CustomTextStyles.titleMediumSFProDisplayBlack900)), SizedBox(height: 22.v), Padding(padding: EdgeInsets.only(right: 39.h), child: CustomPinCodeTextField(context: context, onChanged: (value) {})), SizedBox(height: 13.v), RichText(text: TextSpan(children: [TextSpan(text: "Didn’t receive any code? ", style: CustomTextStyles.labelLargeMedium_1), TextSpan(text: "Resend in 03:00", style: CustomTextStyles.labelLargeErrorContainer)]), textAlign: TextAlign.left), Spacer(), CustomElevatedButton(height: 49.v, text: "Next", margin: EdgeInsets.only(left: 19.h, right: 20.h), buttonStyle: CustomButtonStyles.fillPrimary, onPressed: () {onTapNext(context);}, alignment: Alignment.center), SizedBox(height: 37.v), Align(alignment: Alignment.center, child: GestureDetector(onTap: () {onTapTxtAlreadyhavean(context);}, child: RichText(text: TextSpan(children: [TextSpan(text: "Already have an account? ", style: CustomTextStyles.titleSmallSFProDisplay), TextSpan(text: "Sign In", style: CustomTextStyles.titleSmallSFProDisplayBold_1.copyWith(decoration: TextDecoration.underline))]), textAlign: TextAlign.left)))])))); } 
/// Navigates to the signUpScreen when the action is triggered.
onTapImgIconlyLightOu(BuildContext context) { Navigator.pushNamed(context, AppRoutes.signUpScreen); } 
/// Navigates to the personalInformationScreen when the action is triggered.
onTapNext(BuildContext context) { Navigator.pushNamed(context, AppRoutes.personalInformationScreen); } 
/// Navigates to the signInScreen when the action is triggered.
onTapTxtAlreadyhavean(BuildContext context) { Navigator.pushNamed(context, AppRoutes.signInScreen); } 
 }
