import '../home_one_screen/widgets/homeone_item_widget.dart';import 'package:eco/core/app_export.dart';import 'package:eco/presentation/articles_page/articles_page.dart';import 'package:eco/widgets/custom_bottom_bar.dart';import 'package:eco/widgets/custom_icon_button.dart';import 'package:eco/widgets/custom_outlined_button.dart';import 'package:eco/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';import 'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart';
// ignore_for_file: must_be_immutable
class HomeOneScreen extends StatelessWidget {HomeOneScreen({Key? key}) : super(key: key);

TextEditingController searchFieldController = TextEditingController();

TextEditingController artsyShopNowController = TextEditingController();

TextEditingController berkelyShopNowController = TextEditingController();

TextEditingController artsyShopNowController1 = TextEditingController();

TextEditingController berkelyShopNowController1 = TextEditingController();

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 7.v), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 33.v), Expanded(child: SingleChildScrollView(child: Column(children: [GestureDetector(onTap: () {onTapTwentyNine(context);}, child: Container(margin: EdgeInsets.symmetric(horizontal: 50.h), padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 17.v), decoration: AppDecoration.outlineBlack9002.copyWith(borderRadius: BorderRadiusStyle.circleBorder30), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgSearch, height: 24.adaptSize, width: 24.adaptSize), Opacity(opacity: 0.5, child: Padding(padding: EdgeInsets.only(left: 6.h, top: 3.v), child: Text("Type here to search", style: CustomTextStyles.bodyLargeSFProDisplayBlack900))), Spacer(), CustomImageView(imagePath: ImageConstant.imgVector, height: 16.v, width: 21.h, margin: EdgeInsets.only(top: 6.v, bottom: 2.v)), Container(height: 23.v, width: 30.h, margin: EdgeInsets.only(left: 11.h), child: Stack(alignment: Alignment.topRight, children: [CustomImageView(imagePath: ImageConstant.imgVectorBlack900, height: 15.v, width: 19.h, alignment: Alignment.bottomLeft), Align(alignment: Alignment.topRight, child: Container(padding: EdgeInsets.symmetric(horizontal: 3.h), decoration: AppDecoration.outlineOnSecondaryContainer3.copyWith(borderRadius: BorderRadiusStyle.roundedBorder5), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.end, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 1.v), _buildSearchField(context)])))]))]))), SizedBox(height: 50.v), _buildLatestStack(context), SizedBox(height: 30.v), _buildSeventy(context), SizedBox(height: 30.v), _buildSeventyOne(context), SizedBox(height: 83.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 11.h), child: Text("Shop by categories", style: theme.textTheme.headlineSmall))), SizedBox(height: 24.v), _buildHomeOne(context), SizedBox(height: 36.v), _buildBrowseAllCategoriesButton(context)])))])), bottomNavigationBar: Padding(padding: EdgeInsets.symmetric(horizontal: 7.h), child: _buildBottomBar(context)))); } 
/// Section Widget
Widget _buildSearchField(BuildContext context) { return CustomTextFormField(width: 7.h, controller: searchFieldController, hintText: "3"); } 
/// Section Widget
Widget _buildLatestStack(BuildContext context) { return Align(alignment: Alignment.centerLeft, child: Container(height: 195.v, width: 762.h, padding: EdgeInsets.symmetric(horizontal: 27.h), decoration: AppDecoration.outlineBlack, child: Stack(alignment: Alignment.topRight, children: [Align(alignment: Alignment.centerRight, child: SingleChildScrollView(scrollDirection: Axis.horizontal, padding: EdgeInsets.only(left: 354.h, right: 3.h), child: IntrinsicWidth(child: SizedBox(height: 195.v, width: 351.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgRectangle121, height: 195.v, width: 351.h, radius: BorderRadius.circular(32.h), alignment: Alignment.center), Align(alignment: Alignment.center, child: SizedBox(width: double.maxFinite, child: Row(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgRectangle121195x351, height: 195.v, width: 351.h, radius: BorderRadius.circular(32.h)), Expanded(child: Padding(padding: EdgeInsets.only(left: 280.h, top: 53.v, bottom: 14.v), child: Column(children: [Container(height: 26.v, width: 58.h, decoration: BoxDecoration(color: appTheme.gray5001)), SizedBox(height: 69.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(right: 4.h), child: CustomIconButton(height: 31.adaptSize, width: 31.adaptSize, padding: EdgeInsets.all(6.h), decoration: IconButtonStyleHelper.fillBlack, child: CustomImageView(imagePath: ImageConstant.imgArrowLeftOnsecondarycontainer)))), Expanded(child: Padding(padding: EdgeInsets.only(left: 4.h), child: CustomIconButton(height: 31.adaptSize, width: 31.adaptSize, padding: EdgeInsets.all(5.h), decoration: IconButtonStyleHelper.fillBlack, child: CustomImageView(imagePath: ImageConstant.imgArrowLeftOnsecondarycontainer31x31))))])])))])))]))))), Align(alignment: Alignment.topRight, child: Container(height: 31.v, width: 96.h, margin: EdgeInsets.only(top: 79.v), decoration: BoxDecoration(color: appTheme.gray5001))), Align(alignment: Alignment.bottomRight, child: Container(height: 27.v, width: 70.h, margin: EdgeInsets.only(right: 26.h, bottom: 59.v), decoration: BoxDecoration(color: appTheme.gray5001))), Align(alignment: Alignment.topRight, child: Container(width: 84.h, margin: EdgeInsets.only(top: 50.v, right: 4.h), child: Text("This season’s latest", maxLines: 3, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleLargePlayfairDisplay.copyWith(height: 1.26))))]))); } 
/// Section Widget
Widget _buildArtsyShopNow(BuildContext context) { return CustomTextFormField(width: 88.h, controller: artsyShopNowController, hintText: "Shop now".toUpperCase(), contentPadding: EdgeInsets.symmetric(horizontal: 5.h)); } 
/// Section Widget
Widget _buildBerkelyShopNow(BuildContext context) { return CustomTextFormField(width: 88.h, controller: berkelyShopNowController, hintText: "Shop now".toUpperCase(), contentPadding: EdgeInsets.symmetric(horizontal: 5.h)); } 
/// Section Widget
Widget _buildSeventy(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 21.h), decoration: AppDecoration.outlineBlack, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [GestureDetector(onTap: () {onTapFortySeven(context);}, child: Container(padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 6.v), decoration: AppDecoration.fillOnSecondaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildArrowDown(context), SizedBox(height: 13.v), Text("Artsy", style: CustomTextStyles.titleMediumBlack900), SizedBox(height: 15.v), _buildArtsyShopNow(context), SizedBox(height: 12.v)]))), Container(padding: EdgeInsets.symmetric(horizontal: 13.h, vertical: 10.v), decoration: AppDecoration.fillOnSecondaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildArrowDown1(context), SizedBox(height: 12.v), Text("Berkely", style: CustomTextStyles.titleMediumBlack900), SizedBox(height: 14.v), _buildBerkelyShopNow(context), SizedBox(height: 6.v)]))])); } 
/// Section Widget
Widget _buildArtsyShopNow1(BuildContext context) { return CustomTextFormField(width: 88.h, controller: artsyShopNowController1, hintText: "Shop now".toUpperCase(), contentPadding: EdgeInsets.symmetric(horizontal: 5.h)); } 
/// Section Widget
Widget _buildBerkelyShopNow1(BuildContext context) { return CustomTextFormField(width: 88.h, controller: berkelyShopNowController1, hintText: "Shop now".toUpperCase(), textInputAction: TextInputAction.done, contentPadding: EdgeInsets.symmetric(horizontal: 5.h)); } 
/// Section Widget
Widget _buildSeventyOne(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 21.h), decoration: AppDecoration.outlineBlack, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 6.v), decoration: AppDecoration.fillOnSecondaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildArrowDown(context), SizedBox(height: 13.v), Text("Artsy", style: CustomTextStyles.titleMediumBlack900), SizedBox(height: 15.v), _buildArtsyShopNow1(context), SizedBox(height: 12.v)])), Container(padding: EdgeInsets.symmetric(horizontal: 13.h, vertical: 10.v), decoration: AppDecoration.fillOnSecondaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildArrowDown1(context), SizedBox(height: 12.v), Text("Berkely", style: CustomTextStyles.titleMediumBlack900), SizedBox(height: 14.v), _buildBerkelyShopNow1(context), SizedBox(height: 6.v)]))])); } 
/// Section Widget
Widget _buildHomeOne(BuildContext context) { return StaggeredGridView.countBuilder(shrinkWrap: true, primary: false, crossAxisCount: 4, crossAxisSpacing: 31.h, mainAxisSpacing: 31.h, staggeredTileBuilder: (index) {return StaggeredTile.fit(2);}, itemCount: 4, itemBuilder: (context, index) {return HomeoneItemWidget();}); } 
/// Section Widget
Widget _buildBrowseAllCategoriesButton(BuildContext context) { return CustomOutlinedButton(width: 240.h, text: "Browse all categories".toUpperCase(), margin: EdgeInsets.only(left: 68.h), alignment: Alignment.centerLeft); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
/// Common widget
Widget _buildArrowDown(BuildContext context) { return SizedBox(height: 111.v, width: 126.h, child: Stack(alignment: Alignment.centerLeft, children: [CustomImageView(imagePath: ImageConstant.imgArrowDown, height: 13.v, width: 17.h, alignment: Alignment.topRight, margin: EdgeInsets.only(top: 18.v)), CustomImageView(imagePath: ImageConstant.imgImage1, height: 111.adaptSize, width: 111.adaptSize, alignment: Alignment.centerLeft)])); } 
/// Common widget
Widget _buildArrowDown1(BuildContext context) { return SizedBox(height: 111.v, width: 125.h, child: Stack(alignment: Alignment.centerLeft, children: [CustomImageView(imagePath: ImageConstant.imgArrowDown, height: 13.v, width: 17.h, alignment: Alignment.topRight, margin: EdgeInsets.only(top: 14.v)), CustomImageView(imagePath: ImageConstant.imgImage1111x111, height: 111.adaptSize, width: 111.adaptSize, alignment: Alignment.centerLeft)])); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.articlesPage; case BottomBarEnum.News: return "/"; case BottomBarEnum.People: return "/"; case BottomBarEnum.Me: return "/"; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.articlesPage: return ArticlesPage(); default: return DefaultWidget();} } 
/// Navigates to the searchScreen when the action is triggered.
onTapTwentyNine(BuildContext context) { Navigator.pushNamed(context, AppRoutes.searchScreen); } 
/// Navigates to the homeTabContainerScreen when the action is triggered.
onTapFortySeven(BuildContext context) { Navigator.pushNamed(context, AppRoutes.homeTabContainerScreen); } 
 }
